#!/usr/bin/bash

eval "$(conda shell.bash hook)"
conda activate /home/eliot.finch/eos/env/

declare -A hdf5paths
declare -A selectparampath

basedir="$PWD"

#------------------------

# To try and control the low density behaviour (now that we're not using the
# stitch there) we use a higher reference pressure (which controls where its 
# attached to the crust)
integrate_phi_reference_pressure="3e11"

# Old value (I guess?)
# integrate_phi_reference_pressure="3e10"

#------------------------

CRUST="$PWD/ingo-bps-with-cs2c2-modified.csv"

#-------------------------------------------------
#
# actually construct the conditioned processes
#
#-------------------------------------------------

# Number of EoS realizations we want
NUM_EOS=10000

#------------------------

COMPS=""
COMPS="$COMPS cusa cusb cusc cusd cuse cusf cusg cush cusi cusj cusk cusl cusm cusn cuso cusp cusq cusr cuss cust"

#------------------------

for COMP in $COMPS
do

    tag="${COMP}agn"
    outdir="${PWD}/${tag}"

    echo "--------------------------------------------------"
    echo "PROCESSING $tag"

    hdf5model=${outdir}/gpr_gpr_${tag}.hdf5

    #-------------------------------------

    ### draw from resulting GP

    # echo \
    draw-gpr \
        -v \
        -n $NUM_EOS \
        --output-dir $outdir \
        --tag $tag \
        $hdf5model \
    || exit 1

    process="${outdir}/manifest-${experiment}$tag.csv"
    echo "EoS" > $process

    ### integrate the samples

    for i in $(seq 0 $(($NUM_EOS-1)))
    do

        I=$(python -c "print('%06d'%$i)")
        M=$(python -c "print('%06d'%($i//1000))")
        phipath="${outdir}/DRAWmod1000-$M/draw-gpr_${tag}-${I}.csv"
        outpath="${outdir}/DRAWmod1000-$M/eos-draw-${I}.csv"
	
	# echo \
        integrate-phi \
            -v \
            -o $outpath \
            --sigma-logpressurec2 0.0 \
            --stitch-below-reference-pressure \
            --crust $CRUST \
            --include-cs2c2 \
            $phipath $integrate_phi_reference_pressure \
        || exit 1

        echo $i >> $process ### add this EoS realization to manifest

    done

    #-------------------------------------

done
